import { Question } from '../types';

export const QUESTIONS: Question[] = [
  // Perception (p1–p15)
  { id: 'p1', category: 'perception', text: "What's the first thing people notice about you when you walk into a room?" },
  { id: 'p2', category: 'perception', text: "What do people always get wrong about you?" },
  { id: 'p3', category: 'perception', text: "What's something you do that surprises people who just met you?" },
  { id: 'p4', category: 'perception', text: "What's the most incorrect assumption people make about you?" },
  { id: 'p5', category: 'perception', text: "How do you think strangers would describe your personality?" },
  { id: 'p6', category: 'perception', text: "What's a talent or skill that nobody would guess you have?" },
  { id: 'p7', category: 'perception', text: "What's the biggest difference between who you are at work vs. at home?" },
  { id: 'p8', category: 'perception', text: "What do you think people say about you when you leave the room?" },
  { id: 'p9', category: 'perception', text: "What's something you're secretly proud of that you never talk about?" },
  { id: 'p10', category: 'perception', text: "What energy do you think you give off to people who don't know you?" },
  { id: 'p11', category: 'perception', text: "What's a part of yourself you've never fully shown anyone?" },
  { id: 'p12', category: 'perception', text: "What would your 10-year-old self think of who you are now?" },
  { id: 'p13', category: 'perception', text: "What's one thing you wish people understood about you without you having to explain?" },
  { id: 'p14', category: 'perception', text: "What's the most embarrassing thing that's happened to you in public?" },
  { id: 'p15', category: 'perception', text: "What's something you believe that most people would disagree with?" },

  // Connection (c1–c18)
  { id: 'c1', category: 'connection', text: "What's the most spontaneous thing you've ever done?" },
  { id: 'c2', category: 'connection', text: "What's a secret you've never told anyone in this room?" },
  { id: 'c3', category: 'connection', text: "What's something you've lied about to make yourself seem more interesting?" },
  { id: 'c4', category: 'connection', text: "What's your most irrational fear that you're secretly serious about?" },
  { id: 'c5', category: 'connection', text: "What's the most ridiculous thing you've ever cried about?" },
  { id: 'c6', category: 'connection', text: "What's a habit you have that you'd be embarrassed if anyone knew about?" },
  { id: 'c7', category: 'connection', text: "What's the worst date you've ever been on?" },
  { id: 'c8', category: 'connection', text: "What's something you've done that you still cringe thinking about years later?" },
  { id: 'c9', category: 'connection', text: "What's the pettiest thing you've ever done to get revenge?" },
  { id: 'c10', category: 'connection', text: "What's a lie you've told that somehow spiraled out of control?" },
  { id: 'c11', category: 'connection', text: "What's the most embarrassing song you know every single word to?" },
  { id: 'c12', category: 'connection', text: "What's the most dramatic thing you've done over something minor?" },
  { id: 'c13', category: 'connection', text: "What's the weirdest thing you've ever Googled?" },
  { id: 'c14', category: 'connection', text: "What's your most unpopular opinion about food?" },
  { id: 'c15', category: 'connection', text: "What's a completely irrational deal-breaker you have?" },
  { id: 'c16', category: 'connection', text: "What's the most chaotic thing that's happened to you in the last year?" },
  { id: 'c17', category: 'connection', text: "What's the worst thing you've ever bought on impulse?" },
  { id: 'c18', category: 'connection', text: "What's a compliment you've received that you still think about?" },

  // Reflection (r1–r17)
  { id: 'r1', category: 'reflection', text: "What's a lesson it took you way too long to learn?" },
  { id: 'r2', category: 'reflection', text: "What's something you gave up on that you wish you hadn't?" },
  { id: 'r3', category: 'reflection', text: "What's a decision you made that changed everything?" },
  { id: 'r4', category: 'reflection', text: "What's something you've forgiven yourself for that was hard?" },
  { id: 'r5', category: 'reflection', text: "What's a version of yourself you had to leave behind?" },
  { id: 'r6', category: 'reflection', text: "What's something you're still trying to figure out about yourself?" },
  { id: 'r7', category: 'reflection', text: "What would you do differently if you could relive your teenage years?" },
  { id: 'r8', category: 'reflection', text: "What's the kindest thing someone has ever done for you?" },
  { id: 'r9', category: 'reflection', text: "What's something small that brings you unexpectedly genuine joy?" },
  { id: 'r10', category: 'reflection', text: "What's something you thought you'd never get over that you actually did?" },
  { id: 'r11', category: 'reflection', text: "What's a phase you went through that defined you more than you realized?" },
  { id: 'r12', category: 'reflection', text: "What's a compliment you have a hard time accepting?" },
  { id: 'r13', category: 'reflection', text: "What's your relationship with failure like right now?" },
  { id: 'r14', category: 'reflection', text: "What's something about adulthood nobody warned you about?" },
  { id: 'r15', category: 'reflection', text: "What do you want more of in your life right now?" },
  { id: 'r16', category: 'reflection', text: "What's something you've realized you can't live without?" },
  { id: 'r17', category: 'reflection', text: "What's an expectation of yourself you finally let go of?" },

  // Funny (q1–q171)
  { id: 'q1', category: 'connection', text: 'How long do you think you’d survive in a zombie apocalypse?' },
  { id: 'q2', category: 'connection', text: 'What is your favorite smell?' },
  { id: 'q3', category: 'connection', text: 'Have you ever gone a day without wearing underwear?' },
  { id: 'q4', category: 'connection', text: 'What do you think your last words will be?' },
  { id: 'q5', category: 'connection', text: 'What is it that you keep wanting to smell despite the fact that it doesn’t smell particularly good?' },
  { id: 'q6', category: 'connection', text: 'What secret conspiracy would you like to actually start letting other people know?' },
  { id: 'q7', category: 'connection', text: 'If you can still remember, what are your funniest childhood memories?' },
  { id: 'q8', category: 'connection', text: 'What is the best Wi-Fi name you have seen in your entire life?' },
  { id: 'q9', category: 'connection', text: 'If you were a dog, which breed would you want to be?' },
  { id: 'q10', category: 'connection', text: 'How do you hang toilet paper: over or under?' },
  { id: 'q11', category: 'connection', text: 'Have you ever gone to a corner store and stolen a candy bar?' },
  { id: 'q12', category: 'connection', text: 'How many beers do you think I’d be able to consume?' },
  { id: 'q13', category: 'connection', text: 'What would you do if you won a million dollars?' },
  { id: 'q14', category: 'connection', text: 'What is your Wi-Fi password?' },
  { id: 'q15', category: 'connection', text: 'Why do round pizzas come in square boxes?' },
  { id: 'q16', category: 'connection', text: 'Where was the most embarrassing place you have ever farted?' },
  { id: 'q17', category: 'connection', text: 'Has someone caught you dancing in front of the mirror?' },
  { id: 'q18', category: 'connection', text: 'If I fail a driver’s test, which part will it be?' },
  { id: 'q19', category: 'connection', text: 'Have you ever tried talking to your dog?' },
  { id: 'q20', category: 'connection', text: 'What would you do if you could live forever?' },
  { id: 'q21', category: 'connection', text: 'What would you call a male ladybug?' },
  { id: 'q22', category: 'connection', text: 'Do you like pineapple on your pizza?' },
  { id: 'q23', category: 'connection', text: 'Have you ever been caught cheating on a test?' },
  { id: 'q24', category: 'connection', text: 'In your opinion, how long can my hair grow?' },
  { id: 'q25', category: 'connection', text: 'Can you show me the hidden apps on your phone?' },
  { id: 'q26', category: 'connection', text: 'Who was your first-ever crush?' },
  { id: 'q27', category: 'connection', text: 'Do you sometimes hear certain voices in your head?' },
  { id: 'q28', category: 'connection', text: 'What are three items you might purchase at the grocery store to get strange looks from the cashier?' },
  { id: 'q29', category: 'connection', text: 'What’s the sexiest name you’ve ever heard?' },
  { id: 'q30', category: 'connection', text: 'Do you sleep with the lights on or off?' },
  { id: 'q31', category: 'connection', text: 'What is the silliest thing you’ve ever seen a stranger do in public?' },
  { id: 'q32', category: 'connection', text: 'If you could have a superpower, what would it be?' },
  { id: 'q33', category: 'connection', text: 'What do you typically do when you’re bored?' },
  { id: 'q34', category: 'connection', text: 'What’s one thing your dogs could say that would completely ruin your image if they could talk?' },
  { id: 'q35', category: 'connection', text: 'What’s the most hilarious fact you know?' },
  { id: 'q36', category: 'connection', text: 'Do you have an imaginary friend?' },
  { id: 'q37', category: 'connection', text: 'Can you eat ice cream using your bare hands?' },
  { id: 'q38', category: 'connection', text: 'Have you ever made a prank call to someone you don’t know?' },
  { id: 'q39', category: 'connection', text: 'Have you ever fallen off your bike in front of a huge crowd?' },
  { id: 'q40', category: 'connection', text: 'If you were to be banned from your local library, what would be the reason?' },
  { id: 'q41', category: 'connection', text: 'What are some crazy adventures you want to try in your life?' },
  { id: 'q42', category: 'connection', text: 'Have you ever fallen asleep during class?' },
  { id: 'q43', category: 'connection', text: 'If you could ask me a funny question, what do you think would it be?' },
  { id: 'q44', category: 'connection', text: 'Are you scared of horror movies?' },
  { id: 'q45', category: 'connection', text: 'If you could remove one color in the whole world, what would it be and why?' },
  { id: 'q46', category: 'connection', text: 'What do you think is the worst thing that a person can put on their bio for a dating app?' },
  { id: 'q47', category: 'connection', text: 'Do people drink or eat soup?' },
  { id: 'q48', category: 'connection', text: 'Have you ever been arrested?' },
  { id: 'q49', category: 'connection', text: 'What’s the most embarrassing moment in your entire childhood?' },
  { id: 'q50', category: 'connection', text: 'What would you do if you only had 24 hours to live?' },
  { id: 'q51', category: 'connection', text: 'Who is your all-time celebrity crush?' },
  { id: 'q52', category: 'connection', text: 'What is the wildest fantasy you’ve ever had?' },
  { id: 'q53', category: 'connection', text: 'What do you think your last meal would be if you were on death row?' },
  { id: 'q54', category: 'connection', text: 'Which species would be the rudest if all animals could talk?' },
  { id: 'q55', category: 'connection', text: 'Which person do you know that totally reminds you of a character in a TV show or movie?' },
  { id: 'q56', category: 'connection', text: 'Have you ever forgotten your wallet when you were scheduled to pay for a meal?' },
  { id: 'q57', category: 'connection', text: 'Do you still sleep with a stuffed toy?' },
  { id: 'q58', category: 'connection', text: 'What’s the craziest thing you’ve ever done after getting really drunk?' },
  { id: 'q59', category: 'connection', text: 'What’s your preference: to be buried or cremated?' },
  { id: 'q60', category: 'connection', text: 'Do mermaids have live babies or lay eggs?' },
  { id: 'q61', category: 'connection', text: 'What’s the most creative insult you can think of?' },
  { id: 'q62', category: 'connection', text: 'Have you ever consumed so much alcohol that you passed out?' },
  { id: 'q63', category: 'connection', text: 'Do you think aliens really exist?' },
  { id: 'q64', category: 'connection', text: 'Have you ever been in a secret relationship?' },
  { id: 'q65', category: 'connection', text: 'Who is the first person on your hit list?' },
  { id: 'q66', category: 'connection', text: 'Do you think the sea is salty because the shore never waves back at it?' },
  { id: 'q67', category: 'connection', text: 'Have you ever succeeded in making one of your parents cry?' },
  { id: 'q68', category: 'connection', text: 'Can you tell me the most hilarious joke you’ve ever heard?' },
  { id: 'q69', category: 'connection', text: 'Are you afraid of staying home alone?' },
  { id: 'q70', category: 'connection', text: 'Where would you like to time travel: back to the past or to the future?' },
  { id: 'q71', category: 'connection', text: 'What does the word "ok" mean for you?' },
  { id: 'q72', category: 'connection', text: 'Which of your body parts do you wish to change?' },
  { id: 'q73', category: 'connection', text: 'Have you ever driven someone else’s car without first getting permission?' },
  { id: 'q74', category: 'connection', text: 'What has been the funniest or strangest thing that has happened to you on a first date?' },
  { id: 'q75', category: 'connection', text: 'If you could choose any animated character, who would it be?' },
  { id: 'q76', category: 'connection', text: 'What color would you like if you had to eat a crayon straight from the box?' },
  { id: 'q77', category: 'connection', text: 'Do you believe it is possible to inflate a balloon when underwater?' },
  { id: 'q78', category: 'connection', text: 'What has been the strangest thing a visitor has done at your home?' },
  { id: 'q79', category: 'connection', text: 'Have you ever been in a car crash where you were at fault?' },
  { id: 'q80', category: 'connection', text: 'What musical instrument has the most annoying sound to you?' },
  { id: 'q81', category: 'connection', text: 'Would you like to be married or be in a live-in relationship in the future?' },
  { id: 'q82', category: 'connection', text: 'What’s the biggest lie you have ever told?' },
  { id: 'q83', category: 'connection', text: 'What’s the reason for saying ‘after dark’ when it’s actually really after light?' },
  { id: 'q84', category: 'connection', text: 'What is the funniest thing you’ve ever seen in another person’s house?' },
  { id: 'q85', category: 'connection', text: 'Have you ever secretly taken money from your parents’ pocket or purse?' },
  { id: 'q86', category: 'connection', text: 'If you had to lose your hands or your feet, which would you choose?' },
  { id: 'q87', category: 'connection', text: 'What are the things you would like to change if you became God for a day?' },
  { id: 'q88', category: 'connection', text: 'If you could put one condiment inside your belly button, what would it be and why?' },
  { id: 'q89', category: 'connection', text: 'Who actually tests the specific dog food when they say that it has a new and improved flavor?' },
  { id: 'q90', category: 'connection', text: 'What would be the outcome if the government decided to make everything illegal?' },
  { id: 'q91', category: 'connection', text: 'Are you scared about flying on a plane?' },
  { id: 'q92', category: 'connection', text: 'If life is a video game, what cheat code would you want to use most?' },
  { id: 'q93', category: 'connection', text: 'Have you created a rumor about yourself just to be the talk of town?' },
  { id: 'q94', category: 'connection', text: 'What music would you like to be played at your funeral?' },
  { id: 'q95', category: 'connection', text: 'Where did all the money go if the whole world were in debt?' },
  { id: 'q96', category: 'connection', text: 'Do you have a habit of going for a walk while sleeping?' },
  { id: 'q97', category: 'connection', text: 'What’s the first thing you wash in the shower?' },
  { id: 'q98', category: 'connection', text: 'What do you call a girl named after her mother if a boy named after his father is called Junior?' },
  { id: 'q99', category: 'connection', text: 'What is the worst possible name you might give your child?' },
  { id: 'q100', category: 'connection', text: 'Have you experienced going skinny-dipping before?' },
  { id: 'q101', category: 'connection', text: 'Do you know how to fold a fitted sheet?' },
  { id: 'q102', category: 'connection', text: 'What is your deepest, darkest secret that no one else knows about?' },
  { id: 'q103', category: 'connection', text: 'Between Superman and Goku, who do you think would win?' },
  { id: 'q104', category: 'connection', text: 'Why do we say people work like dogs if they work all day, while dogs do nothing but lie around?' },
  { id: 'q105', category: 'connection', text: 'What are some of your clients’ or colleagues’ nicknames?' },
  { id: 'q106', category: 'connection', text: 'Have you accidentally glued your hands together when doing a craft project?' },
  { id: 'q107', category: 'connection', text: 'Which living individual, outside of your family, do you value the most?' },
  { id: 'q108', category: 'connection', text: 'Have you ever tried to punch me in the face because of what I’ve done?' },
  { id: 'q109', category: 'connection', text: 'What do you want to be in your next birth, and why do you want to be that?' },
  { id: 'q110', category: 'connection', text: 'When was the last time you screwed anything up and no one noticed?' },
  { id: 'q111', category: 'connection', text: 'What’s the worst tagline you can think of for a wart removal cream company?' },
  { id: 'q112', category: 'connection', text: 'What will people be nostalgic for in 500 years?' },
  { id: 'q113', category: 'connection', text: 'Have you ever been called out at school for wearing something embarrassing?' },
  { id: 'q114', category: 'connection', text: 'As a kid, what was your favorite color?' },
  { id: 'q115', category: 'connection', text: 'In terms of appearance, which athlete do you believe most closely resembles you?' },
  { id: 'q116', category: 'connection', text: 'In all honesty, what are some of your guilty pleasures that you are willing to admit?' },
  { id: 'q117', category: 'connection', text: 'What would you do if you could replace all of the grass on the planet with something else, and why?' },
  { id: 'q118', category: 'connection', text: 'Who do you wish you could torture for the rest of your life?' },
  { id: 'q119', category: 'connection', text: 'Which aspects of mine do you admire and which do you despise?' },
  { id: 'q120', category: 'connection', text: 'Would you rather be forced to wear shoes every second of your life or never be able to wear shoes again?' },
  { id: 'q121', category: 'connection', text: 'Who would you appoint as the president of the Internet, and why?' },
  { id: 'q122', category: 'connection', text: 'Have you ever fired a gun?' },
  { id: 'q123', category: 'connection', text: 'Have you ever offered to help anyone else with their homework in return for something specific?' },
  { id: 'q124', category: 'connection', text: 'If we were to have a boxing match, who do you think would win?' },
  { id: 'q125', category: 'connection', text: 'What’s the weirdest thing you’ve given someone as a gift?' },
  { id: 'q126', category: 'connection', text: 'What would you leave me in your last will and testament right now, if you were to die?' },
  { id: 'q127', category: 'connection', text: 'What do you think the first person to milk a cow was actually trying to do?' },
  { id: 'q128', category: 'connection', text: 'How many ants would it take to lift an elephant?' },
  { id: 'q129', category: 'connection', text: 'Have you ever approached a stranger and said something that later turned out to be your best friend?' },
  { id: 'q130', category: 'connection', text: 'Can you tell me one memory that you’ve never shared with me?' },
  { id: 'q131', category: 'connection', text: 'Which movie would you want it to be if your life was a movie?' },
  { id: 'q132', category: 'connection', text: 'What is the soundtrack of your life?' },
  { id: 'q133', category: 'connection', text: 'If Donkey Kong is a monkey, not a donkey, why was he given that name?' },
  { id: 'q134', category: 'connection', text: 'How would you show that you were from the future if you were transported 200 years into the past with no clothing or anything else?' },
  { id: 'q135', category: 'connection', text: 'How do you sleep, with your eyes open or closed?' },
  { id: 'q136', category: 'connection', text: 'Have you ever failed to prepare for an exam before the day you were supposed to take it?' },
  { id: 'q137', category: 'connection', text: 'Who would help who if we were to help each other cheat on a test?' },
  { id: 'q138', category: 'connection', text: 'Do you ever cry while watching an emotional film?' },
  { id: 'q139', category: 'connection', text: 'Have you ever come into contact with human remains?' },
  { id: 'q140', category: 'connection', text: 'Why wasn’t the word “gullible” listed in the dictionary?' },
  { id: 'q141', category: 'connection', text: 'What is the funniest name you have ever heard in real life?' },
  { id: 'q142', category: 'connection', text: 'What are the unwritten laws at our workplace?' },
  { id: 'q143', category: 'connection', text: 'What’s the most amusing thing you’ve seen recently?' },
  { id: 'q144', category: 'connection', text: 'What is the one thing about yourself that you would like to change?' },
  { id: 'q145', category: 'connection', text: 'Can I ask you one question?' },
  { id: 'q146', category: 'connection', text: 'Where does prune juice come from if prunes are dried plums?' },
  { id: 'q147', category: 'connection', text: 'What would your friends and family think if you were arrested without explanation?' },
  { id: 'q148', category: 'connection', text: 'Have you ever had a teacher call you in class when you had no idea what was going on?' },
  { id: 'q149', category: 'connection', text: 'What kind of food would you never offer a tiger?' },
  { id: 'q150', category: 'connection', text: 'Do you like dancing when no one is looking?' },
  { id: 'q151', category: 'connection', text: 'What’s your least favorite planet?' },
  { id: 'q152', category: 'connection', text: 'Why do we refer to an alarm clock as going “off” when it actually turns on?' },
  { id: 'q153', category: 'connection', text: 'What movie’s plot changes entirely only by changing one letter in the title?' },
  { id: 'q154', category: 'connection', text: 'Have your parents ever found you trying to leave the house without permission?' },
  { id: 'q155', category: 'connection', text: 'What do we do when we reach retirement age?' },
  { id: 'q156', category: 'connection', text: 'If you had to choose one fruit, what would you like to be?' },
  { id: 'q157', category: 'connection', text: 'What is the most useless skill you possess?' },
  { id: 'q158', category: 'connection', text: 'What’s your favorite meme?' },
  { id: 'q159', category: 'connection', text: 'Do you think penguins have knees?' },
  { id: 'q160', category: 'connection', text: 'What is it that everybody seems to be doing that makes them look stupid?' },
  { id: 'q161', category: 'connection', text: 'Have you ever cried yourself to sleep because of something that happened that day?' },
  { id: 'q162', category: 'connection', text: 'Which celebrity friendship do you want to embody in our friendship?' },
  { id: 'q163', category: 'connection', text: 'Do you have a habit of saying absurd things while you’re sleeping?' },
  { id: 'q164', category: 'connection', text: 'How would you pull off a perfect crime?' },
  { id: 'q165', category: 'connection', text: 'Before there were dictionaries, where did dictionary makers search for the definitions of words?' },
  { id: 'q166', category: 'connection', text: 'What’s the best inside joke you’ve ever heard?' },
  { id: 'q167', category: 'connection', text: 'How many zombies do you want to kill when the time comes?' },
  { id: 'q168', category: 'connection', text: 'Have you ever lied about your age in order to gain access to a bar or nightclub?' },
  { id: 'q169', category: 'connection', text: 'What color would you pick, if I let you dye my hair any color?' },
  { id: 'q170', category: 'connection', text: 'Can you describe our friendship in three words?' },
  { id: 'q171', category: 'connection', text: 'What sport do you think is the most boring to watch?' },
];

export function getQuestionsForGame(category: string, count: number, usedIds: string[]): Question[] {
  let pool = QUESTIONS.filter(q => !usedIds.includes(q.id));
  
  if (category !== 'mixed') {
    pool = pool.filter(q => q.category === category);
  }
  
  if (pool.length < count) {
    // Reset pool if not enough questions left
    pool = category === 'mixed' ? [...QUESTIONS] : QUESTIONS.filter(q => q.category === category);
  }
  
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
